### PR TITLE
translate Don't feel you aren't smart enough

### PR DESCRIPTION
**Pull request by singcodes**
pull request for sample. may we needs create some wiki for translate ordering. and, what if we adding korean versions for the book links.

### CODE REVIEW

**Comment by strollkim** [comment]
@singcodes  That seems very helpful idea!

**Comment by strollkim** [comment]
@singcodes Could you send the same PR for me, please? I just made some dumb mistake related to rebasing, I think I lost some PR. Sorry to bother you..

**Comment by hoonhoonhoon** [comment]
haha, sure, no problem~

**Comment by hoonhoonhoon** [comment]
oh, It's not necessary PR again, it already done by someone.

**Comment by singcodes** [comment]
oh, It's not necessary PR again, it already done by someone.

**Pull request merged**
