### PR TITLE
Translate 'Why use it?'

### PR DESCRIPTION
**Pull request by hellojaewon**

### CODE REVIEW

**Comment by strollkim** [comment]
Thanks!

**Comment by strollkim** [comment]
@hellojaewon Could you send the same PR for me, please? I just made some dumb mistake related to rebasing, I think I lost some PR. Sorry to bother you..

**Comment by hellojaewon** [comment]
@strollkim Sorry, I'm not good at git commands. How to resend PR again?  If there is no problem,  I will continue the translation and make a PR with different contents.

**Comment by strollkim** [comment]
@hellojaewon There's no problem at all!

**Pull request merged**
